import { createFileRoute, Link } from '@tanstack/react-router'
import {
  Bot,
  FileText,
  Image,
  Mic,
  Music,
  StickyNote,
  Ticket,
  Type,
  Upload,
  Video,
} from 'lucide-react'

import StaticPageLayout from '@/components/StaticPageLayout'
import {
  buildBreadcrumbSchema,
  buildSeoHead,
  buildWebPageSchema,
} from '@/utils/seo'

const DOCS_TITLE = 'Ayles Flow Docs | Canvas, Agent, Models, and Workflows'
const DOCS_DESCRIPTION =
  'Learn how Ayles Flow works, from canvas blocks and uploads to the AI agent, multimodal models, deep research, and PDF generation.'

export const Route = createFileRoute('/docs')({
  head: () =>
    buildSeoHead({
      title: DOCS_TITLE,
      description: DOCS_DESCRIPTION,
      path: '/docs',
      schema: [
        buildWebPageSchema({
          title: DOCS_TITLE,
          description: DOCS_DESCRIPTION,
          path: '/docs',
        }),
        buildBreadcrumbSchema([
          { name: 'Home', path: '/' },
          { name: 'Docs', path: '/docs' },
        ]),
      ],
    }),
  component: Docs,
})

function Docs() {
  return (
    <StaticPageLayout title="Documentation">
      <p>Everything you need to get started with Ayles Flow.</p>

      <section>
        <h2 className="text-xl font-semibold text-zinc-200 mb-4">
          Getting Started
        </h2>
        <div className="space-y-3">
          <div className="rounded-xl border border-zinc-800/60 bg-zinc-900/30 p-5">
            <h3 className="text-[15px] font-semibold text-zinc-200 mb-2">
              1. Create a project
            </h3>
            <p>
              After signing in, click &quot;New Project&quot; on the dashboard.
              Each project is a separate canvas workspace with its own nodes,
              connections, and history.
            </p>
          </div>
          <div className="rounded-xl border border-zinc-800/60 bg-zinc-900/30 p-5">
            <h3 className="text-[15px] font-semibold text-zinc-200 mb-2">
              2. Add blocks to the canvas
            </h3>
            <p>
              Use the sidebar or right-click the canvas to add blocks. Each
              block represents a generation step — image, video, audio, music,
              text, note, ticket, or PDF.
            </p>
          </div>
          <div className="rounded-xl border border-zinc-800/60 bg-zinc-900/30 p-5">
            <h3 className="text-[15px] font-semibold text-zinc-200 mb-2">
              3. Connect and generate
            </h3>
            <p>
              Drag from an output port to an input port to connect blocks. When
              you generate, the output from one block automatically flows into
              the next as input.
            </p>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-zinc-200 mb-4">
          Block Types
        </h2>
        <div className="grid gap-3 sm:grid-cols-2">
          {[
            {
              icon: Image,
              name: 'Image',
              desc: 'Generate images from text prompts. Models: Imagen 4, FLUX 1.1 Pro Ultra, FLUX.2, Recraft V3, HiDream, GPT Image, Ideogram V3, SD 3.5 Medium.',
            },
            {
              icon: Video,
              name: 'Video',
              desc: 'Create videos from text or image inputs. Models: Kling 2.1 Master, MiniMax Video-01, Hailuo-02 Pro.',
            },
            {
              icon: Mic,
              name: 'Audio',
              desc: 'Text-to-speech generation. Models: ElevenLabs V3, Orpheus TTS, Chatterbox.',
            },
            {
              icon: Music,
              name: 'Music',
              desc: 'Generate music tracks from text. Models: MiniMax Music, Lyria 2, CassetteAI.',
            },
            {
              icon: Type,
              name: 'Text',
              desc: 'AI text generation for prompts, scripts, and written content.',
            },
            {
              icon: FileText,
              name: 'PDF',
              desc: 'Structured PDF documents generated by the agent from research output.',
            },
            {
              icon: StickyNote,
              name: 'Note',
              desc: 'Manual text input. Use as a prompt source to feed into other blocks.',
            },
            {
              icon: Ticket,
              name: 'Ticket',
              desc: 'Task descriptions. Use for organizing work and feeding text into pipelines.',
            },
          ].map((item) => (
            <div
              key={item.name}
              className="flex items-start gap-3 rounded-xl border border-zinc-800/60 bg-zinc-900/30 p-4"
            >
              <item.icon size={16} className="text-zinc-500 shrink-0 mt-0.5" />
              <div>
                <h3 className="text-[14px] font-semibold text-zinc-200">
                  {item.name}
                </h3>
                <p className="text-[13px] text-zinc-500 mt-0.5">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-zinc-200 mb-4">AI Agent</h2>
        <div className="flex items-start gap-3 rounded-xl border border-zinc-800/60 bg-zinc-900/30 p-5">
          <Bot size={18} className="text-zinc-500 shrink-0 mt-0.5" />
          <div>
            <p>
              The AI agent lives in the side panel. Tell it what you want in
              plain language and it will add blocks, select models, wire
              connections, and run generations. It can also perform deep
              research — searching the web, reading sources, and synthesizing
              findings into structured reports or PDF documents on the canvas.
            </p>
            <p className="mt-3 text-zinc-500">
              Agent actions: add nodes, connect nodes, update nodes, delete
              nodes, clear the canvas, create PDFs.
            </p>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-zinc-200 mb-4">Uploads</h2>
        <div className="flex items-start gap-3 rounded-xl border border-zinc-800/60 bg-zinc-900/30 p-5">
          <Upload size={18} className="text-zinc-500 shrink-0 mt-0.5" />
          <div>
            <p>
              Upload your own images, audio, video, or PDF files to use as
              inputs. Click the Upload button in the sidebar, select a file, and
              it appears as a completed block on the canvas. Connect it to other
              blocks to use it as input for generation.
            </p>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-zinc-200 mb-3">
          Keyboard Shortcuts
        </h2>
        <div className="rounded-xl border border-zinc-800/60 bg-zinc-900/30 overflow-hidden">
          {[
            { keys: 'Delete / Backspace', action: 'Delete selected nodes' },
            { keys: 'Cmd + C', action: 'Copy selected nodes' },
            { keys: 'Cmd + V', action: 'Paste copied nodes' },
            { keys: 'Cmd + D', action: 'Duplicate selected nodes' },
            { keys: 'Cmd + A', action: 'Select all nodes' },
            { keys: 'Right-click canvas', action: 'Add block context menu' },
            {
              keys: 'Right-click node',
              action: 'Node actions (duplicate, download, delete)',
            },
            { keys: 'Scroll', action: 'Zoom in/out' },
          ].map((item, i) => (
            <div
              key={item.keys}
              className={`flex items-center justify-between px-5 py-3 ${i > 0 ? 'border-t border-zinc-800/40' : ''}`}
            >
              <span className="text-[13px] text-zinc-400">{item.action}</span>
              <kbd className="text-[12px] text-zinc-500 font-mono bg-zinc-800/50 px-2 py-0.5 rounded">
                {item.keys}
              </kbd>
            </div>
          ))}
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-zinc-200 mb-3">Billing</h2>
        <p>
          Ayles Flow uses a credit-based system. Each AI generation costs a set
          number of credits depending on the model. The Free plan includes 10
          credits per month. The Pro plan ($17/mo) includes 500 credits per
          month. Credits reset each billing cycle.
        </p>
      </section>

      <div className="pt-4">
        <p>
          Need help?{' '}
          <Link
            to="/contact"
            className="text-zinc-200 underline underline-offset-2 hover:text-white"
          >
            Contact us
          </Link>
          . You can also browse the{' '}
          <Link
            to="/features"
            className="text-zinc-200 underline underline-offset-2 hover:text-white"
          >
            feature pages
          </Link>{' '}
          for focused walkthroughs.
        </p>
      </div>
    </StaticPageLayout>
  )
}
