/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuasarRouteImport } from './routes/quasar'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LandingSlugRouteImport } from './routes/$landingSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as CanvasProjectIdRouteImport } from './routes/canvas.$projectId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuasarRoute = QuasarRouteImport.update({
  id: '/quasar',
  path: '/quasar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSlugRoute = LandingSlugRouteImport.update({
  id: '/$landingSlug',
  path: '/$landingSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeaturesRoute,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/convex',
  path: '/convex',
  getParentRoute: () => DemoRoute,
} as any)
const CanvasProjectIdRoute = CanvasProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => CanvasRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/start/server-funcs',
  path: '/start/server-funcs',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/start/api-request',
  path: '/start/api-request',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/api/names',
  path: '/api/names',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/start/ssr/',
  path: '/start/ssr/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/start/ssr/spa-mode',
  path: '/start/ssr/spa-mode',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/start/ssr/full-ssr',
  path: '/start/ssr/full-ssr',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/start/ssr/data-only',
  path: '/start/ssr/data-only',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$landingSlug': typeof LandingSlugRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/blog': typeof BlogRouteWithChildren
  '/canvas': typeof CanvasRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quasar': typeof QuasarRoute
  '/terms': typeof TermsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/canvas/$projectId': typeof CanvasProjectIdRoute
  '/demo/convex': typeof DemoConvexRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$landingSlug': typeof LandingSlugRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/quasar': typeof QuasarRoute
  '/terms': typeof TermsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/canvas/$projectId': typeof CanvasProjectIdRoute
  '/demo/convex': typeof DemoConvexRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$landingSlug': typeof LandingSlugRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/blog': typeof BlogRouteWithChildren
  '/canvas': typeof CanvasRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quasar': typeof QuasarRoute
  '/terms': typeof TermsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/canvas/$projectId': typeof CanvasProjectIdRoute
  '/demo/convex': typeof DemoConvexRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$landingSlug'
    | '/about'
    | '/billing'
    | '/blog'
    | '/canvas'
    | '/changelog'
    | '/contact'
    | '/demo'
    | '/docs'
    | '/features'
    | '/privacy'
    | '/quasar'
    | '/terms'
    | '/api/sitemap'
    | '/blog/$slug'
    | '/canvas/$projectId'
    | '/demo/convex'
    | '/features/$slug'
    | '/blog/'
    | '/features/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$landingSlug'
    | '/about'
    | '/billing'
    | '/canvas'
    | '/changelog'
    | '/contact'
    | '/demo'
    | '/docs'
    | '/privacy'
    | '/quasar'
    | '/terms'
    | '/api/sitemap'
    | '/blog/$slug'
    | '/canvas/$projectId'
    | '/demo/convex'
    | '/features/$slug'
    | '/blog'
    | '/features'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/$landingSlug'
    | '/about'
    | '/billing'
    | '/blog'
    | '/canvas'
    | '/changelog'
    | '/contact'
    | '/demo'
    | '/docs'
    | '/features'
    | '/privacy'
    | '/quasar'
    | '/terms'
    | '/api/sitemap'
    | '/blog/$slug'
    | '/canvas/$projectId'
    | '/demo/convex'
    | '/features/$slug'
    | '/blog/'
    | '/features/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingSlugRoute: typeof LandingSlugRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  BlogRoute: typeof BlogRouteWithChildren
  CanvasRoute: typeof CanvasRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRouteWithChildren
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  QuasarRoute: typeof QuasarRoute
  TermsRoute: typeof TermsRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quasar': {
      id: '/quasar'
      path: '/quasar'
      fullPath: '/quasar'
      preLoaderRoute: typeof QuasarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$landingSlug': {
      id: '/$landingSlug'
      path: '/$landingSlug'
      fullPath: '/$landingSlug'
      preLoaderRoute: typeof LandingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/canvas/$projectId': {
      id: '/canvas/$projectId'
      path: '/$projectId'
      fullPath: '/canvas/$projectId'
      preLoaderRoute: typeof CanvasProjectIdRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CanvasRouteChildren {
  CanvasProjectIdRoute: typeof CanvasProjectIdRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasProjectIdRoute: CanvasProjectIdRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

interface DemoRouteChildren {
  DemoConvexRoute: typeof DemoConvexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoConvexRoute: DemoConvexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface FeaturesRouteChildren {
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesSlugRoute: FeaturesSlugRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingSlugRoute: LandingSlugRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  BlogRoute: BlogRouteWithChildren,
  CanvasRoute: CanvasRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRouteWithChildren,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  QuasarRoute: QuasarRoute,
  TermsRoute: TermsRoute,
  ApiSitemapRoute: ApiSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
